Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace AdminPanel.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Areas/Admin/Controllers/ExampleController.cs
using Microsoft.AspNetCore.Mvc;
namespace AdminPanel.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ExampleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Update()
        {
            return View();
        }

        
    }
}

Areas/Admin/Views/Dashboard/Index.cshtml
<div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>
        </nav>
        <div class="container-fluid">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            </div>
        </div>
    </div>
    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Fizi's Website 2025</span>
            </div>
        </div>
    </footer>
    <!-- End of Footer -->
</div>

Areas/Admin/Views/Example/Create.cshtml
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Create Example</h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Example Details</h6>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                <div class="mb-3">
                    <label  class="form-label">...</label>
                    <input  type="text" class="form-control" >
                    <span  class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label  class="form-label">...</label>
                    <input  type="text" class="form-control" >
                    <span  class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label  class="form-label">...</label>
                    <input  type="file" class="form-control">
                    <span  class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i> Create
                </button>
            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/Example/Index.cshtml
<div class="container-fluid">
	<h1 class="h3 text-gray-800 mb-3">Example</h1>
	<div class="mb-4">
		<a asp-action="Create" asp-controller="Example" asp-area="Admin" class="btn btn-success">
			<i class="fas fa-plus"></i> Create
		</a>
	</div>
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Example Table</h6>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-hover table-striped" id="dataTable" width="100%" cellspacing="0">
					<thead class="thead-dark">
						<tr>
							<th>...</th>
							<th>...</th>

							<th>...</th>
							<th>...</th>
							<th class="text-center">Actions</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
							<td class="text-center">
								<img class="img-thumbnail rounded" width="50" src="..." />
							</td>

							<td></td>
							<td></td>
							<td class="text-center">
								<a  class="btn btn-warning btn-sm mx-1">
									<i class="fas fa-edit"></i> Update
								</a>
								<a class="btn btn-danger btn-sm mx-1">
									<i class="fas fa-trash"></i> Delete
								</a>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

</div>

Areas/Admin/Views/Example/Login.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Login</title>

    <!-- Custom fonts for this template-->
    <link href="~/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="d-flex vh-100 justify-content-center align-items-center bg-gradient-primary">
    <div class="col-lg-6 col-md-8 col-10">
        <div class="card o-hidden border-0 shadow-lg">
            <div class="row justify-content-center">
                <div class="col-md-8 col-10">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                        </div>
                        <form class="user" method="POST">
                            <div class="form-group">
                                <input class="form-control form-control-user"    />
                                <span class="text-danger"   ></span>
                            </div>
                            <div class="form-group">
                                <input class="form-control form-control-user"    />
                                <span class="text-danger"   ></span>
                            </div>
                            <div class="form-group">
                                <div class="custom-control custom-checkbox small">
                                    <input class="custom-control-input"    />
                                    <label class="custom-control-label"    ></label>
                                </div>
                            </div>
                            <p class="text-danger text-center">@Html.ValidationMessage("CustomError")</p>
                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                Login
                            </button>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small"   >Create an Account!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/admin/js/sb-admin-2.min.js"></script>

</body>

</html>

Areas/Admin/Views/Example/Register.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Register</title>

    <!-- Custom fonts for this template-->
    <link href="~/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="d-flex vh-100 justify-content-center align-items-center bg-gradient-primary">
    <div class="col-lg-6 col-md-8 col-10">
        <div class="card o-hidden border-0 shadow-lg">
            <div class="row justify-content-center">
                <div class="col-md-8 col-10">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                        </div>
                        <form class="user" method="POST">
                            <div class="form-group">
                                <input class="form-control form-control-user"   />
                                <span class="text-danger"   ></span>
                            </div>
                            <div class="form-group">
                                <input class="form-control form-control-user"    />
                                <span class="text-danger"   ></span>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input class="form-control form-control-user"   >
                                    <span class="text-danger"   ></span>
                                </div>
                                <div class="col-sm-6">
                                    <input class="form-control form-control-user"   >
                                    <span class="text-danger"   ></span>
                                </div>
                            </div>
                            <p class="text-danger text-center">@Html.ValidationMessage("CustomError")</p>
                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                Register
                            </button>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small"  >Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/admin/js/sb-admin-2.min.js"></script>

</body>

</html>

Areas/Admin/Views/Example/Update.cshtml
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Update Example</h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Update Details</h6>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                <div class="mb-3">
                    <label class="form-label">...</label>
                    <input type="text" class="form-control">
                    <span class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label">...</label>
                    <input type="text" class="form-control">
                    <span class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label">...</label>
                    <input type="file" class="form-control">
                    <span class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i> Update
                </button>
            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>AdminPanel</title>
    <!-- Custom fonts for this template-->
    <link href="~/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/admin/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Tables</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Example" asp-action="Index" asp-area="Admin">Example</a>
                    </div>
                </div>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        @RenderBody()
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
        <!-- Bootstrap core JavaScript-->
        <script src="~/admin/vendor/jquery/jquery.min.js"></script>
        <script src="~/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- Core plugin JavaScript-->
        <script src="~/admin/vendor/jquery-easing/jquery.easing.min.js"></script>
        <!-- Custom scripts for all pages-->
        <script src="~/admin/js/sb-admin-2.min.js"></script>
        <!-- Page level plugins -->
        <script src="~/admin/vendor/chart.js/Chart.min.js"></script>
        <!-- Page level custom scripts -->
        <script src="~/admin/js/demo/chart-area-demo.js"></script>
        <script src="~/admin/js/demo/chart-pie-demo.js"></script>
</body>
</html>